query PageApplication($slug: String!) {
	application(slug: $slug) {
		... on Application {
			name
			slug
			metaIcon
			metaDescription
			launchUrl
			oauth2Provider {
				... on OAuth2Provider {
					pk
					clientId
					clientSecret
					clientType
					redirectUris {
						matchingMode
						url
					}
				}
			}
		}
		... on GenericError {
			detail
		}
	}
}
